### ISSUE TITLE
How to reproduce result in live camera feed without saving as video

### ISSUE THREAD

**Issue by ujjawalcse** [bomri/SlowFast#8]
Hi @bomri ,
Thanks a lot for making the repo public.
I want to reproduce result in live camera feed without saving as video.
_For example, I start the camera feed, creating a stack of 16 frames, then providing these frames as input to the model._
For that, I went through data loading code but didn't get it completely where to start.
I'm went through the code `run_net.py` that leads to  `test_net.py` that further leads to `loader.py` for my use case.
Can you please guide me through this?

**Comment by bomri** [comment]
Hi @ujjawalcse,

If you are doing the data creation externally you can basically just skip the loaders and call the forward function of the model with your input in order to get the predictions.

To run inference on some input after loading the model you can use:
`preds = model(inputs)` ([code](https://github.com/bomri/SlowFast/blob/366467aafc856712fdc3e9c4cce8e90969047ee6/tools/test_net.py#L94))

You do need to make sure the input is in the right shape and after transformations, like resizing/cropping, as the model was trained on, and also your input should contain `position_ids` ([code](https://github.com/bomri/SlowFast/blob/366467aafc856712fdc3e9c4cce8e90969047ee6/slowfast/models/video_model_builder.py#L825))

Also, maybe the demo [code](https://github.com/bomri/SlowFast/blob/366467aafc856712fdc3e9c4cce8e90969047ee6/tools/demo_net.py#L96) can help (I haven't tried it myself).

**Comment by ujjawalcse** [comment]
Sure @bomri ,
 I'm trying the same.
