### ISSUE TITLE
Model weights for ViT-B-VTN (1 layer)

### ISSUE THREAD

**Issue by LukasHedegaard** [bomri/SlowFast#9]
Thanks for open-sourcing your work!

Do you still have the model weights for the 1-layer ViT-B-VTN lying around, and would you be willing to add them to the MODEL_ZOO?

It would be greatly appreciated 🙏

**Comment by bomri** [comment]
Hi @LukasHedegaard,
Thank you for your interest in our work.

The models described in our paper were trained using our internal codebase, and we only trained the main ViT-B-VTN with the SlowFast repository in order to share it with the community. So the 1-layer ViT-B-VTN is not compatible with this version of the code.
If you have the Kinetics-400 dataset, you can easily modify the architecture and train this model using the code we published here.

**Comment by LukasHedegaard** [comment]
Nothing comes "easily" when Kinetics is involved 😊
From a reproducibility standpoint, it would be great if you ever decide to open source that internal codebase as well.
Let me know if you ever decide to do so.
